sudo: required
services: 
  - docker

before_install:
  - docker build -t xueszrd/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true -t xueszrd/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-2-843679450762"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"